### ISSUE TITLE
Editorial: Get rid of ReturnIfAbrupt etc, move to ? and ! syntax

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#102]
The SAB spec, being derived from ES6 originally, still uses ReturnIfAbrupt() to propagate failure.

**Comment by domenic** [comment]
While doing this, be sure to also get rid of any "the result of"

**Comment by lars-t-hansen** [comment]
Did not find reason to use "!" anywhere, but ReturnIfAbrupt is gone (along with "the result of").
