### ISSUE TITLE
Is the CopyDataBlockBytes modification meant to be non-normative?

### ISSUE THREAD

**Issue by domenic** [tc39/ecmascript_sharedmem#106]
The modification in https://tc39.github.io/ecmascript_sharedmem/shmem.html#DataTypesValues.SpecTypes.DataBlocks.CopyDataBlockBytes is a NOTE, implying no normative force. Is that correct? I don't know this area well enough to say for sure, but it seems suspicious.

**Comment by littledan** [comment]
Seems like this should be normative text.

**Comment by lars-t-hansen** [comment]
Yes, this should be folded properly into the algorithm.
