### ISSUE TITLE
Type() is not the correct way to test for SharedArrayBuffer

### ISSUE THREAD

**Issue by domenic** [tc39/ecmascript_sharedmem#108]
https://tc39.github.io/ecmascript_sharedmem/shmem.html#IndexedCollections.TypedArray.prototype.setFromTypedArray says

> If Type(x) is SharedArrayBuffer

But SharedArrayBuffers will have Type() of Object, not SharedArrayBuffer.

The correct test here is to check for the presence of an internal slot that only exists on SharedArrayBuffers.

**Comment by lars-t-hansen** [comment]
Not only that, but _x_ is unbound here.
