### ISSUE TITLE
futexWaitOrRequeue() is probably premature optimization - remove?

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#11]
Our pthreads implementation does not use it.  (See https://github.com/kripken/emscripten in the file src/library_pthreads.js, search for futexWait.) I have not yet investigated whether we might want to use it in the future.  But it's one of those hard-to-use APIs that may not be paying for itself as part of the MVP.

**Comment by lars-t-hansen** [comment]
In Issue #77, @pizlonator expressed a desire to remove this function too, expressing similar doubts (premature optimization, uncertain value).

**Comment by lars-t-hansen** [comment]
+1 from me - let's remove it.  (Comments in our emscripten pthreads code say it's not being used because the API is wrong for the original C code - it requires the requeue variant without the value argument.)

Proposed spec change: Remove the section on Atomics.futexWaitOrRequeue and all references to that function.  Clean up any of the "run-time semantics" functions that provide functionality only used by futexWaitOrRequeue.

@binji, reactions?

@juj / @kripken, any concerns about this re MUSL / emscripten?

**Comment by binji** [comment]
Better to remove. It can always be added later if we find that it is useful.

**Comment by kripken** [comment]
I don't see any usages in emscripten, no worries from me.
