### ISSUE TITLE
Editorial: "A List of elementSize" does not make sense

### ISSUE THREAD

**Issue by domenic** [tc39/ecmascript_sharedmem#110]
I am not sure what this is meant to mean, but here is my guess at phrasing that fits with the existing spec better:

> 1. Let rawValue be a List of elementSize resulting from ReadSharedMemory(block, byteIndex, accessAtomic, elementSize)

becomes

> 1. Let _rawValue_ be ReadSharedMemory(block, byteIndex, accessAtomic, elementSize).
> 2. Assert: _rawValue_ is a List of size _elementSize_.

**Comment by lars-t-hansen** [comment]
That wording actually follows the current ES spec (at least as found in GetValueFromBuffer).  I do not care for it myself but figured, when in Rome...  Will clean up.
