### ISSUE TITLE
Editorial: SharedDataBlockID mechanism seems confusing and unnecessary

### ISSUE THREAD

**Issue by littledan** [tc39/ecmascript_sharedmem#114]
Seems like you're giving the data blocks "ID"s to formalize the fact that they're referring to the same underlying memory, without letting anything in the "heaps" of the different Agents reference each other. But the mechanisms seem a bit magical. The core of the correspondence between the Agents is

> Let G be an address-free identifier for block. All agents in the same agent cluster must use the same value for G for any given block.

Why not instead say that they have the same Data Block? Data Blocks are already not exposed to JS.

**Comment by lars-t-hansen** [comment]
I think this is probably a good idea.  The Shared Data Block ID was a notational shorthand, but in the current draft it is used much less often than it used to be, namely, it is used in TypedArray.prototype.set() to compare data block identities, and in GetWaiterList() to look up a WaiterList for the location (G,i).  I'll experiment with some prose.
