### ISSUE TITLE
Editorial: Atomic ops inner functions could use a little shoring up

### ISSUE THREAD

**Issue by littledan** [tc39/ecmascript_sharedmem#118]
Just being pedantic here. E.g., from Atomics.add:

> Let `add` denote a semantic function of two number arguments that returns the sum of the arguments.

What does this do on overflow, etc? Is this JS `+`, which returns a larger Number, and then SetValueInBuffer casts it down? Maybe best if you either refer to `+` explicitly define an abstract operation (probably a one-liner) for this purpose.

**Comment by jfbastien** [comment]
FWIW in C++ unsigned simply wrap, and signed is two's complement. It would be most convenient for SAB to have the same semantics.

**Comment by littledan** [comment]
I think letting SetValueInBuffer do the wrapping would end up doing the same thing.

**Comment by lars-t-hansen** [comment]
For all the data types we currently care about (Int64 would be different) it is sufficient to say that `+` and `-` perform operations on Number, and to let SetValueInBuffer perform the truncation.  For `and`, `or`, and `xor` there is no overflow so the wording would be a little different.

**Comment by lars-t-hansen** [comment]
I am going with this phrasing for add, subtract, and, or, xor, and exchange:

Let `xor` denote a semantic function of two Integer arguments that computes the same result as the ECMASCript function `(a,b) => a^b`.

**Comment by littledan** [comment]
(playing dumb) What's an Integer? I've only ever heard of Numbers, and SetValueInBuffer with strings like "Uint16" as the Element Type in Table 50.

**Comment by lars-t-hansen** [comment]
How about "integer"?  The ES7 spec uses unqualified "integer" many places.

**Comment by littledan** [comment]
Well, continuing to be excessively pedantic, the question is where do the integers (lowercase) come from? GetValueFromBuffer returns a Number, not a mathematical value. Why not call them that?

**Comment by lars-t-hansen** [comment]
I don't think I want to involve myself in a metaphysical discussion about the origin of integers this morning.  If you want Number, you shall have Number.  When I suggested [Ii]nteger it was to make the spec simpler to understand, since the inputs (and outputs) will all be integer values, not any arbitrary Number values.  It makes no difference to the implementation though.
