### ISSUE TITLE
Address-free wording

### ISSUE THREAD

**Issue by jfbastien** [tc39/ecmascript_sharedmem#124]
I'd clarify the wording for address-free. It currently says:

> Data blocks (ES7 6.2.6)
> [...]
> A Shared Data Block has an identity (for the purposes of equality testing Shared Data Block values) that is address-free: it is tied not to the virtual addresses the block is mapped to in any process, but to the set of locations in memory that the block represents. Shared Data Blocks can also be distinguished from Data Blocks.

As reference, the C++ standard says:

>  Operations that are lock-free should also be address-free. That is, atomic operations on the same memory location via two different addresses will communicate atomically. The implementation should not depend on any per-process state. This restriction enables communication  by memory that is mapped into a process more than once and by memory that is shared between two processes.

The difference between the two is that C++'s effective heap is usually a single virtual address space (though C++ knows neither about heap nor virtual addresses).

For SAB I'm wondering if the same physical page could be mapped onto different SABs. The current wording doesn't reflect this possibility because it only mentions virtual addresses (which I think is somewhat clunky anyways).

Further, I think it's worth following C++'s lead and mentioning "The implementation should not depend on any per-process state", though I'd make that "per-Shared Data Block state".

SAB supports non-lock free operations on 1 and 2 byte accesses, which implies global state (hidden in the implementation) to ensure atomicity if the accesses aren't lock-free.

**Comment by lars-t-hansen** [comment]
There is currently no mechanism that allows "the same physical page to be mapped onto different SABs" by the user program, indeed the idea does not exist in ES and it pained me to introduce virtual addresses in the paragraph you quote.

Clearly, considering a SharedArrayBuffer as an ES object, multiple distinct SABs in the same agent can reference the same block of physical locations but whether that block must be one mapping or could be two or more mappings probably should be decided by the combination of the memory model and the CPU architecture.

The intent is certainly that it should be as if it is a single mapping but whether the memory model actually requires that is a little doubtful.  It would be more obvious if ReadSharedMemory (in its speculation) and WriteSharedMemory (in its queueing of writes) would be explicit about resolving the _block_ to its underlying bytes (ie mapping it to physical addresses).  But I think that takes us in the wrong direction.

I have to mull this over further.

**Comment by lars-t-hansen** [comment]
Shared Data Block identity and equality are perhaps underspecified.  It was actually better before, with the tag _G_, since that made equality testing simple to understand (just a comparison of serial numbers obtained from some global source).  Let's punt on that for the moment and instead look at a couple of other rules:

Suppose A and B are Shared Data Blocks.
- If A equals B then A and B reference the same sequence of storage locations in memory
- If A does not equal B then A and B reference disjoint sequences of storage locations in memory

That should get rid of "virtual addresses" in the spec (and the possible issue of memory being mapped multiple times though I believe that is a red herring for ES).

(The prohibition on per-process state in C++ is actually pretty weird -- surely the language semantics should determine what's a legal implementation technique?)

**Comment by jfbastien** [comment]
> (The prohibition on per-process state in C++ is actually pretty weird -- surely the language semantics should determine what's a legal implementation technique?)

Yeah that should probably be a note in the standard. But then again, C++ has "as-if" rule which makes everything a note ;-)

**Comment by lars-t-hansen** [comment]
The spec still has the old prose here.  I'll try to address this.

**Comment by lars-t-hansen** [comment]
Filed a PR for a simple clarification, which is probably enough for the time being.

**Comment by lars-t-hansen** [comment]
The clarification was merged.

**Comment by pcordes** [comment]
@lars-t-hansen wrote:

> (The prohibition on per-process state in C++ is actually pretty weird -- surely the language semantics should determine what's a legal implementation technique?)

Just for the record:  It *is* a note in the C++ standard.

It's describing the intent of the standard that lock-free atomic objects can be safely used in shared memory between separate processes, not just between threads in the same process that share the entire address space.  It's not normative, and only applies to implementations where it makes sense.

Related: https://stackoverflow.com/questions/18321244/is-c11-atomict-usable-with-mmap

https://stackoverflow.com/questions/49848793/genuinely-test-stdatomic-is-lock-free-or-not suggests using separate processes with shared memory as a way to test whether an implementation is really lock-free, regardless of what `is_lock_free` reports.

(And BTW, I only found this thread while googling for the technical meaning of "address free", and whether that term alone covers still working when two processes don't share most of their address space, including the global hash table of locks for atomic objects.  In that case it shouldn't matter or help if each process mmaps the shared memory segment to a different base or not.)
