### ISSUE TITLE
8 byte atomics

### ISSUE THREAD

**Issue by jfbastien** [tc39/ecmascript_sharedmem#126]
The current spec doesn't allow 8-byte atomics. I'd like an explanation of why that's the case (DISCUSSION.md?).

I understand that having 64-bit integer support is a prerequisite, but that's not clear for developers looking to move lock-free code (e.g. using 2 pointers in a lock-free datastructure, or using doubles) to JS through transcompilation.

**Comment by lars-t-hansen** [comment]
There are no 8-byte atomics, because there is no 8-byte integer type in ES and I could not get traction for floating-point atomics.  Developers looking to move lock-free code using 8-byte atomics need to look again.

I'll add a brief section about this to DISCUSSION.md, it's worth mentioning.

**Comment by jfbastien** [comment]
Looked at your change: spot on, thanks!
