### ISSUE TITLE
Suspend timeout

### ISSUE THREAD

**Issue by jfbastien** [tc39/ecmascript_sharedmem#130]
What's the type of `timeout`? It says "nonnegative number", so I assume a floating-point value? Shouldn't that be spelled "Number"?

Also, can it be a NaN?

Infinity seems fine.

**Comment by lars-t-hansen** [comment]
It's a floating point number, yes.  I can change it to Number.

It can be infinite but not NaN: the value is laundered in Atomics.wait() before we get here.  I'll clarify.
