### ISSUE TITLE
Real world usage examples

### ISSUE THREAD

**Issue by OleksandrChekhovskyi** [tc39/ecmascript_sharedmem#136]
Given that there is an upcoming meeting to discuss moving shared memory spec to stage 3, it would likely be of interest to the people involved to see some real usage examples.

Here is what I'm building:
http://statebuilder.com/

It's a 4X strategy game (in spirit of Civilization). Demo mode only currently. Loading is not optimized yet (loads files over HTTP sequentially), so it might spend few seconds on the black screen on start, that's expected.

**Comment by lars-t-hansen** [comment]
Thanks.  I have some simple demos myself, but it's possible they are a little stale.  They're referenced from DEMOS.md.  Maybe you can turn this ticket into a PR against DEMOS.md?  Create a new section, eg, "Web apps using shared memory" or something like that and then we can have this as a subsection.  A short paragraph + a URL seems about right.

**Comment by OleksandrChekhovskyi** [comment]
Pull request submitted.

**Comment by lars-t-hansen** [comment]
Pull request merged.
