### ISSUE TITLE
Thread-local storage

### ISSUE THREAD

**Issue by jfbastien** [tc39/ecmascript_sharedmem#14]
I'm no fan of thread-local storage because it's an overly-general mechanism, but [it has its uses](http://wg21.link/n4376) and is used by real code. One of the goals of shared memory in JavaScript is to compiled _existing_ C/C++ code, and that code relies on TLS in many ways. Not exposing TLS means that some code needs to be rewritten, may not be as efficient, and may not support all the features some developers expect.

Should:
- The initial version of JavaScript shared memory support TLS?
- A subsequent version of JavaScript shared memory support TLS?

If/when it is exposed, should:
- TLS be exposed as-is (a "current thread pointer" function call, effectively returning a pointer into the array buffer)?
- TLS be accessed through a WebWorker's context?

**Comment by lars-t-hansen** [comment]
I'm opposed to adding direct TLS support without compelling needs being demonstrated first, for either version.

TLS should be pretty trivially available (in asm.js) by a callout to JS, I think, since the JS heap of an agent is really all TLS.  In the emcscripten mapping of C/C++ there's a fair amount of logic that's handled by that mechanism.  If the performance of that mechanism turns out to be poor then we should try to fix the performance first.

**Comment by jfbastien** [comment]
To alleviate my concern: is there a no-code-modification implementation of TLS in current Emscripten?

**Comment by lars-t-hansen** [comment]
I don't know, but we can try to summon @juj - he would know.

**Comment by juj** [comment]
Yes, we do have support for thread local storage in Emscripten! See https://github.com/kripken/emscripten/commit/fb4b1e9fa104e5b1ee12a613e8153e82e811ff87 . The `pthread_getspecific` and `pthread_setspecific` functions are supported. I think the implementation works quite beautifully, the only variable that is currently local to each thread is the id of that thread. Then the data lookup is done by dereferencing the thread id, which is actually a pointer to a thread structure in the Emscripten heap (https://github.com/kripken/emscripten/commit/fb4b1e9fa104e5b1ee12a613e8153e82e811ff87#diff-cb58003b1d0e81ef04f061e479929712R6).

There's a laundry list of two pending items regarding TLS for me: https://github.com/kripken/emscripten/issues/3502 and https://github.com/kripken/emscripten/issues/3504 , and they should both be doable within the current structure of the SAB spec, so I am all happy here.

**Comment by lars-t-hansen** [comment]
I consider the issue resolved.
