### ISSUE TITLE
Related research

### ISSUE THREAD

**Issue by jbondc** [tc39/ecmascript_sharedmem#148]
I recently read "DRFx: An Understandable, High Performance, and Flexible Memory Model for Concurrent Languages":
http://web.cs.ucla.edu/~todd/research/toplas16.pdf

I'm curious if ideas in DFRx are useful for #133.

**Comment by lars-t-hansen** [comment]
Been curious about that myself, but unlike you I've yet to read it :)  Thanks for the reminder.

**Comment by lars-t-hansen** [comment]
A moot point now, cc @syg.
