### ISSUE TITLE
Editorial: Clarify the sense in which agents in a cluster all have the "same" [[CandidateExecution]]

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#152]
During execution the [[CandidateExecution]] is immutable, so it's fine for "same" to be a little vague, but really [[CandidateExecution]] has mutable fields during "construction", so it's probably best if this is clarified somehow by stating explicitly that the Agent Record contains a copy or that the Agent Records all carry a reference to the record, not the record itself.

**Comment by lars-t-hansen** [comment]
@syg, I believe this was fixed?

**Comment by syg** [comment]
The current language says:

> All agents in an agent cluster share the same candidate execution record in its Agent Record's [[CandidateExecution] field, which is initialized to an empty candidate execution Record.

I didn't think too hard about clarifying further. Though now that I look at it, the "empty candidate execution" definition is missing the initialization of [[EventLists]] for all agents in the agent cluster.

**Comment by syg** [comment]
I spelled it out: https://github.com/syg/ecma262/commit/296d8d23550ed462efda423794896d51b3d63ac4

**Comment by lars-t-hansen** [comment]
Issue tracked by ecma262.
