### ISSUE TITLE
DOM/HTML integration: How can the agent cluster grow?

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#154]
An agent creates a SharedArrayBuffer.  In a DOM/HTML setting, which other agents can it share that memory with?

The spec requires that memory be shared only so that agents in the cluster are suspended or terminated together.  The canonical situation where that is not the case is for a window and a sharedworker it communicates with - that worker may remain alive even if the window is closed, or suspended because it's pushed into its tab's history.  Then, if the window is holding a lock (in shared memory) the sharedworker may deadlock.

The rule of thumb has therefore been that a cluster has to comprise a window and its dedicated workers (recursively) or a SharedWorker and its dedicated workers (recursively) and that attempts to share memory outside such clusters must be prevented.

But are there other situations where the co-termination restriction is not violated?  I'm thinking of a top-level window and a nested element such as a window in an iframe, or similar situations.

**Comment by lars-t-hansen** [comment]
Also needs to be reflected in the main spec's "Web browser embedding" section, which is currently sketchy.

**Comment by annevk** [comment]
As far as I can tell in such situations it's not the agent that's being terminated, but it's just a single global object within that agent.

**Comment by lars-t-hansen** [comment]
@annevk, can you elaborate a little?  I don't understand your comment.

**Comment by annevk** [comment]
I was responding to

>  I'm thinking of a top-level window and a nested element such as a window in an iframe, or similar situations.

As you already addressed the shared worker scenario.

While you can remove an iframe (and thereby make its global inaccessible), any objects you hold references to, including the global, will be there still.

**Comment by annevk** [comment]
Remaining agent termination issues are https://github.com/whatwg/html/issues/2581 and https://github.com/tc39/ecma262/issues/401.

**Comment by lars-t-hansen** [comment]
Closing this, as issues have migrated to more appropriate repos.
