### ISSUE TITLE
Slides as PDF files?

### ISSUE THREAD

**Issue by rauschma** [tc39/ecmascript_sharedmem#158]
Would you mind adding PDF version of all slides? And to include the slides from the latest TC39 meeting? Thanks!

**Comment by syg** [comment]
@rauschma The slides that were presented in the Nov 2016 TC39 are available [here](http://tc39.github.io/ecmascript_sharedmem/presentation-nov-2016.pdf) and [in the repo](https://github.com/tc39/ecmascript_sharedmem/blob/master/tc39/presentation-nov-2016.pdf). The LaTeX source is also in the repo.
