### ISSUE TITLE
Update tutorial now that SAB in transfer map is prohibited

### ISSUE THREAD

**Issue by Elchi3** [tc39/ecmascript_sharedmem#164]
The [tutorial](https://github.com/tc39/ecmascript_sharedmem/blob/master/TUTORIAL.md) currently mentions:

> The creator can share this memory with the worker by *transfering* it using the standard ```postMessage``` semantics, where a second argument to ```postMessage``` contains the values to be transfered:
> ```js
> w.postMessage(sab, [sab])
> ```

I guess this should be updated in the light of #98 and [bug 1302036](https://bugzilla.mozilla.org/show_bug.cgi?id=1302036).

**Comment by lars-t-hansen** [comment]
Fixed this.
