### ISSUE TITLE
stage3 or stage 4?

### ISSUE THREAD

**Issue by yanyu0517** [tc39/ecmascript_sharedmem#167]
I check [Finished Proposals](https://github.com/tc39/proposals/blob/master/finished-proposals.md) and find this feature has forward into stage 4, but still be stage 3 in ReadMe.

**Comment by syg** [comment]
SAB is stage 4 and has been merged into the main [ecma262 spec text](https://tc39.github.io/ecma262/#sec-sharedarraybuffer-objects).
