### ISSUE TITLE
Add readAsSharedArrayBuffer to FileReader

### ISSUE THREAD

**Issue by topicus** [tc39/ecmascript_sharedmem#169]
To allow workers play with file contents currently you have three options (maybe more): 
- Post a message to the worker with the File (structured cloning is costly).
- Read the file as an array buffer and transfer it to the worker context (it's no longer accesible from other contexts).
- Read the file as an array buffer and copy it's contents to a shared array buffer (still a copy is needed).

If you need to parallelize tasks over file contents (e.g. parsing a big csv file) there is no way to do it without perform a copy which is costly operation when you deal with large files.

**It would be great to have a readAsSharedArrayBuffer to read the file straight in a shared array buffer and thus avoid the copy.**

Is there any other way to perform this with the current specs that I'm missing?

Sorry if this is not the right place for this proposal.

**Comment by littledan** [comment]
I think the right place for this proposal would be against the FileAPI at https://github.com/w3c/FileAPI/issues . This specification is just for the JavaScript side, not any associated I/O libraries.

**Comment by topicus** [comment]
@littledan Thank you, moving this.
