### ISSUE TITLE
[asm.js] Avoid alignment masks?

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#19]
[This captures a discussion on the old spec.  The issue is probably resolved - we're going to stick with the current syntax where an explicit shift is required, at the cost of the alignment mask - but since the comment thread is open still I'm preserving it here.]

**Dan Gohman / 6:38 PM Mar 9:**

This (ie the E>>K form of the index for atomic operations) is the form from which the need for alignment masks arises. The explicit shift is combined with the implicit shift of the array index to form the final address and the result is a bitand to mask off the low bits.

I understand the concern of keeping the API concise, and am fine if it's decided that the cost of alignment masks is worth not having to make all the Atomics operations per-type, but it'd be useful to mention this in the rationale.
Show less

**Lars Hansen / 7:14 PM Mar 9:**

The cost should be the same as for aligned heap accesses, which will also go via the int32 view. I understand that it costs an instruction, but I don't understand why it is any harder to get rid of that instruction here than in heap accesses.

**Dan Gohman / 7:45 PM Mar 9:**

Yes, it's exactly the same situation as we have today with normal scalar loads and stores. The only thing that's different is that Atomics have an API which is not yet standardized, giving them an opportunity for them to avoid masks altogether if we choose (at the cost of API simplicity).

The mask is an extra instruction, and on x86, it also increases register pressure because the and instruction clobbers its input.

Of course, atomic operations are often much more expensive than plain loads and stores, so the extra cost is not as significant. And, Atomics don't otherwise have a reason to be per-type, so it would make the API much more verbose. It's certainly a tradeoff; I just want us to make the decision explicitly.

**jyasskin / 8:32 PM Mar 9:**

dgohman, any suggestions for what to do if someone writes a mis-aligned Atomics use under your suggestion?

**Dan Gohman / 9:17 PM Mar 9:**

Probably just say that the operation is not single-copy atomic when called with an index doesn't have a satisfactory integer factor.

That's obviously not awesome, so it's another thing to weigh in the tradeoff.

**Dan Gohman / 9:23 PM Mar 9:**

On the other hand though, the present asm.js alignment-mask semantics are that we fudge the byte index down to the nearest alignment boundary and then do the access. This is also not awesome.

**Comment by jfbastien** [comment]
My grep-fu is failing: which part of the current spec talks about atomic alignment?

**Comment by sunfishcode** [comment]
It's implied by typed arrays being indexed by element.

**Comment by jfbastien** [comment]
Ah OK, this confused me:

> The issue is probably resolved - we're going to stick with the current syntax where an explicit shift is required

"Explicit" in that it's implicit in the typed array used? ;-)

**Comment by sunfishcode** [comment]
Typed arrays have an implicit shift to convert from element index to byte offset. asm.js adds an explicit shift to convert from byte offset to element index.

**Comment by jfbastien** [comment]
Ah I get it now, thanks!
