### ISSUE TITLE
[asm.js] How will removing SharedTypedArray work?

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#20]
Once SharedTypedArray disappears and we instead use TypedArray on SharedArrayBuffer, the asm.js compiler is not going to get a direct signal - by the view construction - that shared memory is being used.  An indirect signal must take its place.  This signal is only useful when generating code for Atomics operations, in which we want to omit the checks that the underlying memory is shared.  So in a sense, it is enough to say that if an Atomics operation is imported (or perhaps if one is invoked anywhere, though it amountsto much the same), then we can assume that shared memory will be used, allowing the optimization.

However, to make the optimization for Atomics legal, the check has to be hoisted to where the views are created.  If we check there that the memory is a SharedArrayBuffer and throw if it is not (as we must), then the asm.js execution does not have the same behavior as the JS execution: the JS execution will fail only if any Atomics operations are actually invoked on non-shared memory.

Supposing that that discrepancy is undesirable, then a further hack is possible: an asm.js module that imports any Atomics operations will only _validate_ if there is a new _ValidateHeap_ clause preceding the module exports.  This clause takes the form of an expression statement that will fail if the heap is not shared memory.  In its simplest form this directive could be `atomics_load(anyView, 0);`.  By construction this access would dominate (dynamically) all atomic accesses in the module; it would perform the necessary type check; it would have the same behavior in both asm.js and plain js.

In another context @lukewagner suggested that we could change the asm.js definition so that the module creates the heap it works on.  I'm not opposed to that, but my proposal is less wrenching, I think.

**Comment by lukewagner** [comment]
Oops, I just realized why my proposal (creating the SAB inside the asm.js module) can't work: after you `postMessage` a SAB to another worker, that worker's asm.js _must_ take that SAB as a parameter; it can't create its own.

Ok, so I like your idea of: an asm.js module is shared iff it imports stdlib atomics.  We don't need to do that validation-time hack, though: we can simply have linking fail if you import atomics and you're given a non-SAB (or you don't import atomics and you are given a SAB).  This seems like a pretty minor change, actually.

**Comment by lars-t-hansen** [comment]
Right, just to be clear, the idea of the validation-time hack was an attempt to keep JS and validated-asm.js dynamic semantics in sync.  I had the impression that was desirable.  But if it's not a hard requirement I'm all for getting rid of the extra headache!

**Comment by lukewagner** [comment]
I don't know of any such requirement.  This situation is fairly symmetric with plain non-shared ABs: we emit all this code assuming we're actually operating on an AB but if you hand us a pizza at link time, we have no option but to throw up our hands and restart from scratch.

**Comment by lars-t-hansen** [comment]
I see, another static link condition with fallback.  Nice.  I will note that.

**Comment by lars-t-hansen** [comment]
The ideas in this thread have been incorporated into the new asm.js addendum.  I will keep this thread open until code changes land in Firefox, however.

Firefox bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1084248 (remove racy behavior in the engine)
https://bugzilla.mozilla.org/show_bug.cgi?id=1176214 (remove SharedTypedArray)
