### ISSUE TITLE
ecmarkup creates possibly undesirable cross references

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#26]
In the (current) section on "With atomic access to..." there is a phrase, "Shared Data Block ID", which is defined elsewhere in the document.  Ecmarkup recognizes "Data Block" as a standard phrase and hyperlinks it to E262 on ecma-international.org.  This is wrong.

Need to check if this still happens with the latest ecmarkup, and if it turns out to be something that still happens, either figure out how to disable it or to file an ecmarkup bug - the behavior is not at all desirable in its current form.

**Comment by lars-t-hansen** [comment]
Still with us.

**Comment by bterlson** [comment]
I missed this issue too :( Feel free to ping me when you discover ecmarkup issues, I am happy to help and fix them for you!

**Comment by lars-t-hansen** [comment]
No worries - arguably this was user error, and introducing some dfns fixed it.
