### ISSUE TITLE
Forward progress guarantees for Jobs

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#28]
The spec draft currently adds a weak forward progress guarantee for ES6 jobs.

The guarantee should be strengthened, and it can be done so in the same manner as in C++.  For the latter, see [this paper](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4439.pdf).

**Comment by lars-t-hansen** [comment]
A proposal in the HTML spec (allow workers to be created with specific guarantees about forward progress, in order to allow resource management) pertains to this:  https://github.com/whatwg/html/issues/851.

**Comment by lars-t-hansen** [comment]
Updated the spec language slightly to account for agents with shared execution threads.

**Comment by lars-t-hansen** [comment]
The section on lock-freedom now contains a note contrasting it to wait-freedom (though it does not take that any further).

**Comment by jfbastien** [comment]
Circling back, the following was added to C++17: http://wg21.link/p0296r2

**Comment by jfbastien** [comment]
@lars-t-hansen do you believe this has been addressed? In https://github.com/tc39/ecmascript_sharedmem/issues/5#issuecomment-136377233 you said:

> Once the spec goes to TC39 it will become natural to file the missing forward progress guarantee as a bug against ES262.

Now that we're at Stage 4, is this something that needs to be addressed?

**Comment by lars-t-hansen** [comment]
@jfbastien, thanks for picking up this thread again.  cc @syg.

The current spec language is here: https://tc39.github.io/ecma262/#sec-forward-progress.  That language is indicative of the intent but informal compared to C++ and probably hasn't changed very much since the present issue was filed.

I don't feel great urgency to strengthen it further since, unlike C++, we have a largely operational semantics and can talk about "making a step" in the semantics as making forward progress, but do argue the point if you disagree.

**Comment by lars-t-hansen** [comment]
I'll take the thumbs-up as a sign that we're done here.
