### ISSUE TITLE
Should TypedArray constructors be extended to allow them to allocate shared memory

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#30]
In the current spec, TypedArray constructors that allocate ArrayBuffer have not been changed in any way to allow them to create a SharedArrayBuffer.  (One could imagine adding a flag, for example.)

The question is whether the constructors should be changed in that way.  I happen to think they should not be, but I'm wondering if there are opinions to the contrary.

**Comment by littledan** [comment]
How about "not at first"? I don't see any use cases for this, but if we do find use cases, then we can create other constructor paths/flags as needed. The ArrayBuffer constructor path seems like the most meaningful one to ensure works with SharedArrayBuffer, and that's (implicitly) handled.

**Comment by lars-t-hansen** [comment]
Right.  When I'm writing code the new Int32Array(new SharedArrayBuffer(4*n)) idiom feels OK, and is explicit.  Shared memory is the exception to the rule, which is unshared.

**Comment by lars-t-hansen** [comment]
No disagreements in seven months, let's be done.
