### ISSUE TITLE
Should TypedArray static methods be allowed to allocate shared memory?

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#31]
Currently the TypedArray static methods that allocate ArrayBuffers (TypedArray.of, TypedArray.from) cannot allocate SharedArrayBuffers.  

I happen to think this is best, but I'm curious if there are opinions to the contrary.

**Comment by littledan** [comment]
Same as my answer to #30--good to leave it out until we have a strong motivating use case.

**Comment by lars-t-hansen** [comment]
Agreed.
