### ISSUE TITLE
Allow embedding-specific constraints on futexWait

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#36]
During the September 2015 TC39 meeting, concerns were expressed by several members (perhaps foremost among themYehuda Katz) about allowing blocking on the browser's main thread.

Browser implementers have also expressed a concern that browsers are not engineered in such a way that blocking on the main thread is viable: the main thread performs work on behalf of other threads and a blocked main thread can deadlock the system.

This work item is about investigating several things:
- whether the API can be extended to allow an embedding to signal that blocking is not allowed on a certain thread (probably easy)
- what the consequences of such a change would be (probably hard)

There was agreement at the meeting that we should not bake the concept of "main thread" into the spec; something more general is called for.

The consequences of such an API are perhaps difficult to predict.  If a program can't block on the main thread it can still spinloop with atomics.  If atomics are taken away on the main thread, the program will tend to spinloop without atomics, creating racy programs that are not portable and probably not reliable in the face of jit optimization.  The only "fix" for that is to take away shared memory on the main thread (eg allow it to allocate and transfer a SharedArrayBuffer), but that will cause signficant pain elsewhere.  Etc.

**Comment by taisel** [comment]
Was able to sporadically, yet extremely rarely, glitch out the futex api, such that the glitch state survived page refreshes, but not reboots of firefox nightly: https://bugzilla.mozilla.org/show_bug.cgi?id=1227494

Wonder if that's related to the issues with being able to block the main thread.

**Comment by lars-t-hansen** [comment]
The immediate cause of that glitch is probably a bug in the locking code in the application, I've commented in Bugzilla.  That said, there might also be a Firefox problem, if the problem survives page refreshes.  (Let's keep the Firefox-specific discussion in Bugzilla so that we don't have to comment both places.)

A blocked main thread is a general concern, it is like an infinitely-looping script.  In most browsers such a block should normally be broken by the slow-script interrupt, which is in some sense adequate.  However, if (in the browser implementation) the main thread is in charge of network communication, graphics and UI, etc, there may be all sorts of unintuitive effects of allowing the main thread to block for long.  Suppose a worker performs an xmlhttprequest that is (in the browser implementation) delegated to the main thread; meanwhile the main thread is futexWaiting for the worker to provide it with some data that the worker will gets from processing data it receives off that xmlhttprequest.  This will deadlock the browser until the main thread blocking is broken by the slow-script interrupt, at which point the user program is broken since the main thread is no longer waiting for data from the worker.

**Comment by taisel** [comment]
Was able to spot the theoretical bug you pointed out, although I have not been able to repro the issue as well (before/after the code changes). It was an extremely weird issue that occurred only once, hence I tried documenting it.

**Comment by binji** [comment]
> The only "fix" for that is to take away shared memory on the main thread (eg allow it to allocate and transfer a SharedArrayBuffer), but that will cause signficant pain elsewhere. Etc.

Agreed, though the pain may not be too bad. In effect, NaCl has this model -- all communication between the NaCl module (which can use threads/shared memory) and JavaScript must be via postMessage. This was tedious, but workable. For most APIs this will work (but again, tedious), though it is almost certainly too slow for WebGL. Perhaps transferable canvases will be the solution?

**Comment by taisel** [comment]
The usefulness of AudioWorkers depends on this. Streaming PCM between main thread and an AudioWorker would need this for much lower latency and overhead.

**Comment by lars-t-hansen** [comment]
Added a little bit of machinery to allow a thread not to suspend:

https://github.com/lars-t-hansen/ecmascript_sharedmem/commit/51021b9af689f5f093a00065348ba4afb8550222

**Comment by taisel** [comment]
Was able to convert the lock based code to lockless code, so there shouldn't be any issues running IodineGBA as demo for shared mem for vendors that disable waiting on main thread: https://github.com/taisel/IodineGBA/commit/5852bd56e3fcd9eb83183ebb0e26d94d222ad86d

Gist there was replacement of earlier lock based buffers into ring buffers with producer/consumer counters only writable by one side each.

**Comment by lars-t-hansen** [comment]
There is a writeup summarizing some current experience and thoughts about the way forward here:
https://github.com/lars-t-hansen/ecmascript_sharedmem/blob/master/issues/FutexWaitOnMainThread.md

**Comment by lars-t-hansen** [comment]
The original issue (no futexWait on main thread) is pretty much resolved.  It's likely that "no shared memory on the main thread" will come back along the way to Stage 3 (in fact I expect it will) but that should be a new bug.

**Comment by taisel** [comment]
No shared memory on main thread is being proposed? It already has definite use cases there, to the point that it's on the turf of offthread WebGL.

**Comment by lars-t-hansen** [comment]
Some people want no-shared-memory-on-main, though I don't.  There've been experiments with proxying (Ben brought up PNaCl above, there's some work going on in the emscripten space to automate it but last I heard it was not done) and it sort of works most of the time, but there are known overheads that can be hard to get rid of.  I think (a) somebody has to champion the restriction and (b) there has to be an investigation of the consequences, if such a champion appears.
