### ISSUE TITLE
Should vendors make support for SAB a prerequisite for AudioWorkers?

### ISSUE THREAD

**Issue by taisel** [tc39/ecmascript_sharedmem#42]
My only concern with audio workers for the web audio API was the inherent added latencies when passing an audio stream cross thread. After testing SAB use streaming from a webworker to the main ui with the deprecated scriptprocessornode, I found that concern to no longer be true. If all vendors that support AudioWorkers implement SAB first, then I hope that will allow less fallback and shimming. 

Anyone else think there should be a prerequisite for the order SAB and AudioWorkers land in?

**Comment by lars-t-hansen** [comment]
I think that if you want to make that argument you need to be filing bugs on individual browsers' bug trackers, to bring it to the attention of the right people (AudioWorker people).
