### ISSUE TITLE
Memory model imprecision: blanket prohibition on impementation introducing races

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#48]
The prose for `PutValueInBuffer()` currently has an ad-hoc rule that outlaws read-modify-write of a larger datum than the target size.  This rule prevents the introduction of a certain type of race.  But there are other transformations that could also create races, see Issue #37.  The better fix here is likely to have a blanked prohibition on creating new races, and to back that up with Notes or a separate writeup of how that can happen - speculation, RMW, failing to assume ordering effects of unknown functions, maybe more.

**Comment by jfbastien** [comment]
I'm a bit wary of "don't introduce new races": it may make sense to introduces races which can't be observed without the program already being racy. Reordering regular load/store is a simple example of observable changes only when races are already present, my hunch is that it's possible to observe good optimizations if the program is already racy.

**Comment by lars-t-hansen** [comment]
I think we agree, though I take the point - this needs to be expressed more carefully than I did.  At the same time I think we need for a racy program to be able to become non-racy in some well-defined way (I had a writeup about that but I can't find it right now) and these new races that might be introduced should not get in the way of that.

**Comment by lars-t-hansen** [comment]
I think the (forthcoming) draft now addresses this properly, by curtailing specific optimizations such as introduced writes.  Let's reopen this bug or open new ones if the new language is deemed to be insufficient.
