### ISSUE TITLE
Joint Firefox/Chrome test suite

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#50]
There's a small test suite here but both teams have test programs and test code that could be cleaned up and landed here.  That should happen (conv. with Brad and JF).

Test suite here should be compatible with test262 so that it can just drop in when it is needed.

**Comment by jfbastien** [comment]
cc @binji who's managed to run your test suite in Chrome, and was looking at Chrome's testing.

**Comment by lars-t-hansen** [comment]
Most Mozilla "plain JS" (as opposed to asm.js) test cases have been incorporated into the test suite already (originating from https://hg.mozilla.org/mozilla-central/file/tip/js/src/jit-test/tests/atomics).  These test just single-thread behavior: coercions, etc.

Google "plain JS" test cases are here: https://chromium.googlesource.com/v8/v8/+/master/test/mjsunit/harmony/atomics.js.  Ditto.

Test262 requires a copyright assignment form to be signed (eventually), and whoever's incorporating code into the test suite in this repo needs to be (pre-)bound by that: http://tc39.github.io/test262-cla/.  @binji, I'll leave it up to you whether you want to try to incorporate any Google test cases here, meanwhile I'll incorporate tests here for your test cases that made Firefox fail.

TODO: There are some test cases here for inter-thread behavior, but we need more (I have more but some of them use edgy ES6 features not yet quite available in Chrome, like "let" in non-strict code).  And we want to incorporate larger demo programs.

**Comment by lars-t-hansen** [comment]
I've started populating a new subdirectory in the proposal repository, 'test262/'.  This contains (initially) the test cases from the test-shell/ subdirectory, translated to tc39/test262 style though with a custom HTML test runner for the time being (runner.html).  See README in that directory for more.  I expect that the test-shell directory will be removed eventually.

**Comment by lars-t-hansen** [comment]
Work item: Issue #78 requires a change to the test suite.

Work item: Issue #63 might require a change to the test suite, though more likely there's no test case for that yet.

**Comment by lars-t-hansen** [comment]
Closing this because it is largely finished.  Please open new bugs for individual test cases that should be added.
