### ISSUE TITLE
Should shared memory be accessible on the browser's main thread

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#54]
(This question comes up from time to time so let's track it.)

Some people have expressed opposition to exposing racy shared memory to the main thread of a web browser, on the general principle that it exposes the main thread to nondeterminism.  Technically, such exposure occurs if the main thread can create a TypedArray on a SharedArrayBuffer and some other agent is able to modify that SharedArrayBuffer's memory while the main thread is able to read it.

Several approaches are possible to prevent the main thread being exposed to those types of races, here is a cluster of ideas:
- It could be illegal for the main thread to construct TypedArrays on shared memory.  The main
  thread would still be able to construct SharedArrayBuffers and transfer those to and from agents,
  which is useful but not racy.  It is easy to implement and spec.  Usability is probably "OK" - all
  initialization
  work would be delegated to a dedicated worker.  But it means main-thread DOM APIs cannot
  access shared memory at all.
- It could be illegal for the main thread to access shared memory unless all the workers that share
  that memory are quiescent.  This would build on the previous solution, along with a new primitive, say,
  `Atomics.callWithSharedMemory(sab, callback)`, where the callback receives a TypedArray on the
  SAB that is rendered useless once the callback returns.  The primitive could either succeed
  immediately or the callback would be invoked when the workers are all quiescent.  I'm not sure how
  hard this is to implement, or how expensive it is to use.  (Quiescent would include agents waiting in their
  event loop or in futexWait.)  "Nontrivial" is my best guess.  Usability is strictly better than the above
  case, and DOM APIs may now take a TypedArray, but I don't know if utility is much better.
- The above can combine with a mechanism where agents that share the SAB explicitly surrender the
  SAB so that the main thread can use it.  This reduces the implementation burden on the main-thread
  side (and increases it on the worker side) and is probably not a burden for use, since a level of 
  cooperation is required to make `callWithSharedMemory` a useful primitive anyway.
- The previous point can be combined with a technique that surrenders the SAB (in a region, say)
  without blocking the worker.  This is a lot like detaching, temporally, and has many of the problems
  of "sharing" memory by transfering it back and forth (ie, clunky to use in practice).

For asm.js the usefulness stops after the first bullet, probably.  In practice it means that almost all computation takes place in a cluster of workers that communicates by messages with the main thread for the use of DOM APIs.  See notes below on proxying.

For handwritten-JS the techniques in the other bullets might be employed as optimizations to avoid proxying overhead.  These techniques in principle allow for no copying to happen, at the cost of blocking all workers (or blocking them from using that memory) while the main thread is working.

The main reason to support the no-shared-memory-on-main-thread restriction is security, on the assumption that a main-thread consuming DOM API that assumes its memory cannot be shared can be fooled with a well-placed time-of-check-to-time-of-use attack.  While that attack must be taken seriously, it is being addressed in other ways, notably by making it explicit whether a DOM API can accept shared memory (Issue #38 and linked bugs against WebIDL); implementations can also guard themselves systematically (internally in Firefox, for example, ArrayBuffer-ish data are represented as a fat pointer that does not allow shared and unshared memory to be confused).

Regarding proxying: With proxying (the main thread does DOM and I/O) data will largely be copied in the process of invoking a proxied operation, either the worker code copies data into a transferable ArrayBuffer or the data are copied by the postMessage itself.  This can work: PNaCl does it, some asm.js code does it in Firefox, and there's some support for it in emscripten (I'm not sure what the status of that is).  I am told that PNaCl has a custom non-postMessage-based protocol to support the proxying.  It's clunky but affordable in most cases; in cases where it's not affordable there needs to be some kind of workaround that amounts to coming up with some other type of shared memory that is more controllable.  

FWIW, I'm personally against this restriction, I think it makes programming with shared memory much harder than it needs to be, in return for very little - if any - gain.

Edit Feb 10: corrected a typo.

**Comment by taisel** [comment]
Would the DOM API be on a case by case usage depending on which API is used and elected into accepting SAB? Or would it be a blanket complication for all of main thread?

Edit: I'm asking it in this manner to see what is being leaned towards, I do realize work is being done to add checks to the API.

**Comment by lars-t-hansen** [comment]
I've had little to do with the DOM APIs myself thus far, and IIUC Firefox has adapted only a few WebGL APIs and only in a fairly ad-hoc fashion based on actual needs.  IMO, with virtual certainty the DOM APIs will be adapted on a case-by-case basis.

**Comment by lars-t-hansen** [comment]
@erights, I think you raised this issue at the last meeting.  Any input you have on the above writeup or in general would be welcome here.

**Comment by erights** [comment]
@lars-t-hansen , one thing I remain especially confused about: Assuming we impose no such restriction on reading and writing, but we wish to prohibit the main thread from blocking. What would the normal user-level patterns look like for non-racy reads and writes that could not block?

**Comment by lars-t-hansen** [comment]
@erights, the patterns wouldn't look quite normal.  In practice, while workers communicate among themselves through shared memory with futexWait and futexWake, they communicate with the main thread by sending it messages.  It is possible to write safe multithreaded code this way, the costs change though because messages are slow.  For communicating "coarse" values (eg, "all the workers are waiting in a barrier now") the messages work fine, but for communicating "fine" values (eg, "a worker consumed an element from a queue and it has space for a new one") the messages are probably not quite affordable - depending on the application, of course.  There are optimizations (batching, waiting for a short time in a spin loop, etc).  My experience has been that the data structures for communicating between workers are not quite the same as those for communicating between workers and the main thread.  So complexity increases, but we remain safe.

There's a simple example of such code here:
https://github.com/lars-t-hansen/parlib-simple/blob/master/src/asymmetric-barrier.js

A more complex example is a data-parallel framework:
https://github.com/lars-t-hansen/parlib-simple/blob/master/src/par.js

The latter program exhibits a similar pattern to the barrier: the main thread sets up a computation in shared memory and then communicates to the workers that they should run; when they are done they communicate back that they have left results in shared memory.

**Comment by lars-t-hansen** [comment]
Barring any further discussion - we've had a six-month comment period - I consider this matter closed.
