### ISSUE TITLE
Can an object be sent between agents?

### ISSUE THREAD

**Issue by erights** [tc39/ecmascript_sharedmem#68]
I would have thought not. postMessage clones and SAB traffics only in data. However, https://axis-of-eval.org/shmem/agents-formatted.html says:

> With the exception of the backing memory for SharedArrayBuffer objects this communication cannot cause any ECMAScript object memory that is mutable in any agent to become shared between agents, **and** the ECMAScript implementation is not required to preserve object identity if **an object value is sent from one agent to another** and back.
> [emphasis added]

The first part of this sentence implies, correctly I think, that the second part of the sentence makes no sense. What sending of object values from one agent to another do you mean? Are you drawing a distinction between "object" and "object value"? If so, how can an object value have identity?

**Comment by lars-t-hansen** [comment]
The intent is to state that there is no way to share memory other than through the backing store of SAB.

I will attempt to clarify the language, though @domenic was objecting to the whole paragraph, IIRC, and [wanted to remove it](https://github.com/tc39/ecmascript_sharedmem/issues/27#issuecomment-187360439) (in the middle).  So the right fix may be to remove it as being irrelevant to this particular spec.

**Comment by lars-t-hansen** [comment]
The section containing the offending prose was removed.
