### ISSUE TITLE
Unintended happened-before hole breaks transitivity

### ISSUE THREAD

**Issue by erights** [tc39/ecmascript_sharedmem#70]
At http://tc39.github.io/ecmascript_sharedmem/shmem.html#Atomics.WithAtomicAccessTo

> 1. A and B are both atomic accesses to identical access ranges, B follows A in the synchronization order, **and B reads the value written by A**, or
> 2. A happens before C and C happens before B (transitivity).
>    [emphasis added]

The last part of point 5 breaks the intended transitivity. If B follows A in the synchronization order but does not read any value written by A, but C happens before A, does C happen before B? I hope so but I don't think it can be derived from this spec language.

**Comment by lars-t-hansen** [comment]
This part of the spec is not yet finished.  I need another week.  What you're pointing to is one of the open issues.

**Comment by lars-t-hansen** [comment]
Sorry, misspoke here.  Simple typo.

**Comment by lars-t-hansen** [comment]
> If B follows A in the synchronization order but does not read any value written by A, but C happens before A, does C happen before B? I hope so but I don't think it can be derived from this spec language.

@erights 

I misspoke again; the spec is correct as it is (I believe).  The section defines happens-before, "<".  A < B if A's write is read by B.   But if B simply follows A in the synchronization order it does not follow that A < B.  The two events could be unrelated.  However, as the synchronization order is total the two events must be ordered by it.

Consider two threads T1 and T2 and two atomic variables V1 and V2.  T1 writes to V1 and T2 writes to V2.  These two write events, being atomic, must be ordered by the synchronization order, but that does not create a happens-before relationship between them.

(Will revert the check-in I just made.)

**Comment by erights** [comment]
Just to be sure we understand each other, what is your answer to the question at the start of the thread:

 If B follows A in the synchronization order but does not read any value written by A, but C happens before A, does C happen before B?

**Comment by lars-t-hansen** [comment]
> If B follows A in the synchronization order but does not read any value written by A, but C happens before A, does C happen before B?

Not necessarily, because B and A are not related other than by the synchronization order, which does not by itself create the happens-before relationship.

**Comment by erights** [comment]
Since this consequence is intended, I'm happy to see the issue closed. I don't quite understand the implications though. Perhaps best clarified verbally at the upcoming mtg.
