### ISSUE TITLE
What wake order does wait-queue order guarantee?

### ISSUE THREAD

**Issue by erights** [tc39/ecmascript_sharedmem#73]
At http://tc39.github.io/ecmascript_sharedmem/shmem.html#Atomics.futexWakeOrRequeue

> Atomics.futexWake wakes up some agents that are sleeping in the wait queue and moves other waiting agents to the back of the queue.

This issue didn't occur to me until I read this. Currently, I think you guarantee a deterministic wake order among things queued in the same queue. Is this intentional? If so, great, but worth checking.

**Comment by lars-t-hansen** [comment]
Yes, that is on purpose.  Sadly, if we move to use [synchronics](https://axis-of-eval.org/shmem/synchronic-formatted.html) this property will disappear; the nondeterminism inherent in that proposal is key to the synchronics having much better performance than futexes.
