### ISSUE TITLE
What is observable about "accessible"?

### ISSUE THREAD

**Issue by erights** [tc39/ecmascript_sharedmem#74]
At http://tc39.github.io/ecmascript_sharedmem/shmem.html#WebBrowserEmbedding.CloneAndTransfer

> A Shared Data Block remains accessible so long as at least one SharedArrayBuffer object references it in some agent.

What is the intended observable difference that this statement makes? In a different non-normative document I remember you mentioned refcounts, but I took that as an implementation issue rather than a normative spec issue -- and was glad not to see it in the spec. Non-normative implementation notes in the spec are fine too of course. Should this be one? A good litmus test is: How would one write a conformance test for this issue?

**Comment by lars-t-hansen** [comment]
The entirety of section 8 is informative (see section heading).  That said, you're probably right that this is an implementation note.  I'll propose a fix.

**Comment by lars-t-hansen** [comment]
The prose disappeared with the recent rewrite of Section 8, and we won't miss it.
