### ISSUE TITLE
Mutable array shared where constant array was intended

### ISSUE THREAD

**Issue by erights** [tc39/ecmascript_sharedmem#75]
At https://github.com/tc39/ecmascript_sharedmem/blob/master/TUTORIAL.md

> Suppose the creator of the shared memory wants to share a large _constant_ array of prime numbers with its workers. It allocates the memory, fills it, and sends it:

Did you forget an `Object.freeze` or something? What about the following code makes in constant?

**Comment by lars-t-hansen** [comment]
It's constant by the way it's used, ie, it's not intended to be updated.  Feel free to suggest a better term.  No freezing was intended.

**Comment by erights** [comment]
"share a large array of ... , with no intent of further modification."

This avoids implying that any of the participants is prevented from modifying. This pattern has that hazard, so it needs at least to have that hazard clearly.

**Comment by lars-t-hansen** [comment]
Works for me.  I will incorporate that wording.

**Comment by lars-t-hansen** [comment]
Fixed.
