### ISSUE TITLE
Spec language suggestion: Use better spec wording for some atomic algorithms

### ISSUE THREAD

**Issue by littledan** [tc39/ecmascript_sharedmem#90]
For Atomics.{and,or,sub,xor,exchange}, there is text saying "do this except here do that". It would be cleaner if you instead were slightly more explicit. For an example, which I didn't get any pushback on, in SIMD.js I used a higher order abstract algorithm, e.g., http://tc39.github.io/ecmascript_simd/#simd-add calls SIMDBinaryOp. What do you think of this wording?

**Comment by lars-t-hansen** [comment]
Sure, I can do something like that.
