### ISSUE TITLE
Integrate spec text into ES text with change bars?

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#92]
In Issue #77 @waldemarhorwat writes:

> Is there a way to see the integrated proposal as an ES6 document with change bars? I'm having a hard time with the mechanics of reading the proposal as only a delta, and it's very difficult to tell if something more should be included but is missing. 

@domenic @bterlson Does ecmarkup have that kind of functionality?

**Comment by lars-t-hansen** [comment]
Domenic says "use INS and DEL tags".

**Comment by lars-t-hansen** [comment]
@waldemarhorwat, how does [this version](https://axis-of-eval.org/shmem/changebars/spec.html) look to you?

@littledan, would it be appropriate to offer the proposal to the committee in this form?  I sure would prefer not to have to maintain two sets of proposal text.

**Comment by littledan** [comment]
So far, seems like most proposals have proceeded with just an external document, not a diff/PR against the main spec. SharedArrayBuffer has mostly been developed in this form, and I think it's good. ins and del tags are useful when modifying existing internal algorithms or grammar, but I don't know if SAB runs into any of those. The work of integrating directly into the main spec text tends to be done some time after Stage 3. I don't think you need to maintain the PR against the spec--that sounds like a lot of work with all the rebasing.

**Comment by bterlson** [comment]
Please do not maintain a PR against the spec. Once your spec is stage 4 (or when you're pushing for stage 4) is the appropriate time for producing the spec PR.

**Comment by lars-t-hansen** [comment]
OK, fair enough.  I'll consider the matter closed until the proposal advances.

**Comment by lars-t-hansen** [comment]
As a compromise (and because I think it is an improvement) I have -- in selected cases, notably several altered algorithms -- copied a small amount of text from ES262 into the shared memory draft spec and marked the diff from ES262 using INS/DEL tags.  I have also identified the base revision of ES262 for that.  As it was, the spec was out of sync with current ES262 and was hard to understand.
