### ISSUE TITLE
Subtlety with Atomics.isLockFree() - add note or fix normative language

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#94]
(From a conversation with @jfbastien)

The normative language for [isLockFree](https://tc39.github.io/ecmascript_sharedmem/shmem.html#Atomics.isLockFree) is probably on the weak side.  On all hardware we care about _it will work_ to use word-width RMW atomics to implement byte and halfword atomic operations if the architecture does not have instructions for that (MIPS, POWER).  However, it is probably the case that on such platforms isLockFree(1) and isLockFree(2) should still return false: a RMW implementation could have to spin indefinitely due to modifications occuring outside the data that's being accessed.  That violates the intent of the primitive.  Neither the SAB spec nor the Agents spec has normative language to pin this restriction down; the notes in the SAB spec strongly hint at the restriction but could be better, and a non-normative note is really inappropriate here.

**Comment by jfbastien** [comment]
That brings up an interesting point: maybe you want to detail lock-free versus wait-free versus obstruction-free in the spec (related to #28).

Lock-free doesn't imply wait-free in this case, so I don't think I agree with what you wrote.

The issue I see with guaranteeing `isLockFree(1)` and `isLockFree(2)` is the lack of 1-byte or 2-byte `cmpxchg` or ll/sc instructions on some architecture: having these instructions is really what restricts lock-freedom.

**Comment by lars-t-hansen** [comment]
I may well have misunderstood you yesterday.  Let's try again.

If, on all hardware we care about, a byte RMW can be safely implemented using a word RMW (say) because the hardware ensures that a non-atomic access on a byte adjacent to the atomic byte happens in some well-defined interaction with the atomic update (ie, on x86 the CPU would lock the bus for the atomic update and prevent the racing store; on ARM the update monitor would observe the unsynchronized store if it arrived before the synchronized store), is there any reason that platform would not have isLockFree(1)==true?

(It may of course be that ARM/MIPS/POWER do not give that interaction well-defined meaning.)

**Comment by jfbastien** [comment]
Agreed with you, lack of smaller `cmpxchg` or ll/sc don't disallow `isLockFree` for that smaller size (assuming HW we care about offer that guarantee, which I think is the case).
