### ISSUE TITLE
"futexWait" and "futexWake" are not-great names, use "wait" and "wake" instead?

### ISSUE THREAD

**Issue by lars-t-hansen** [tc39/ecmascript_sharedmem#95]
I think this counts as a review comment that it has been left to me to write down...  (I forget who was the originator, it was over dinner.)

While it is true that `futexWait` and `futexWake` are modeled on Linux futexes, we don't point to Linux for the semantics -- we define those in the spec.  Indeed our semantics can (and probably do) diverge from the Linux semantics in some details.  It might be better to rename these functions and just call them `wait` and `wake`.

One argument for keeping the existing names is that they serve as warning signs ("here be dragons"), and allows the simpler names to be reserved for future, higher-level facilities.

@littledan, @pizlonator, @jfbastien - opinions?

**Comment by jfbastien** [comment]
`wait` / `wake` sound good, and considering we'll likely add `pause` it seems to make sense.

**Comment by pizlonator** [comment]
+1. This is a good change. 

-Filip

**Comment by lars-t-hansen** [comment]
@binji, any concerns?

**Comment by binji** [comment]
nope, sgtm

**Comment by taisel** [comment]
Time to break out the github reactions feature.
