### ISSUE TITLE
Worker Priority Hinting?

### ISSUE THREAD

**Issue by taisel** [tc39/ecmascript_sharedmem#97]
It seems fit to provide a developer with ways to control resource contention among multiple workers. That being said, it's clear to me the priority level setting should be restricted against valid ranges in relation to main thread. It's also my understanding that Audio Workers are the exception to this restriction, to avoid latency issues (Or was that solved another way?).

This needs to be hashed out heavily, even if not incorporated into the SHM+Atomics specification directly. 

Should we discuss this or leave it for another time?

**Comment by lars-t-hansen** [comment]
Try the HTML group.  I have on my plate to move a bunch of issues I filed in https://www.w3.org/Bugs/Public/show_bug.cgi?id=29039 to github, see discussion (also about hinting) on https://github.com/whatwg/html/issues/851.  You would probably want to reference the first one of those at least if you do file something.

**Comment by taisel** [comment]
Oh nice, didn't realize it got rolled up into that spec.
